---

- name: Gather facts, for debugging
  setup:
    gather_subset:
      - 'network'
  tags: [ never, facts ]

- name: Show configuration
  vars: 
    msg: |
      freeipa_server_hostname:       '{{ freeipa_server_hostname }}'
      freeipa_server_fqdn:           '{{ freeipa_server_fqdn }}'
      freeipa_server_domain:         '{{ freeipa_server_domain }}'
      freeipa_server_realm:          '{{ freeipa_server_realm }}'
      freeipa_server_ip:             '{{ freeipa_server_ip }}'
      freeipa_server_idstart:        '{{ freeipa_server_idstart }}'
      freeipa_server_ds_password:    '{{ freeipa_server_ds_password | default('UNDEFINED') }}'
      freeipa_server_admin_password: '{{ freeipa_server_admin_password | default('UNDEFINED') }}'
      -----
      freeipa_server_install_options: {{ freeipa_server_install_options }}
  debug: 
    msg: "{{ msg.split('\n') }}"       
  tags: [ never, debug ]

- name: Display all variables/facts known for a host
  debug:
    var: ansible_default_ipv4
  tags: [ never, debug_all ]
