---

- name: Run the FreeIPA Server installer
  args:
    creates: /etc/ipa/default.conf
  command: >
    {{ freeipa_server_install_base_command }}
    {{ freeipa_server_install_options | join(' ') }}
  notify: restart ipa services
