---

- name: Gather OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - vars

- name: Show configuration
  vars:
    msg: |
      freeipa_server_hostname:       '{{ freeipa_server_hostname }}'
      freeipa_server_fqdn:           '{{ freeipa_server_fqdn }}'
      freeipa_server_domain:         '{{ freeipa_server_domain }}'
      freeipa_server_realm:          '{{ freeipa_server_realm }}'
      freeipa_server_ip:             '{{ freeipa_server_ip }}'
      freeipa_server_idstart:        '{{ freeipa_server_idstart }}'
      freeipa_server_ds_password:    '{{ freeipa_server_ds_password | default('UNDEFINED') }}'
      freeipa_server_admin_password: '{{ freeipa_server_admin_password | default('UNDEFINED') }}'
      -----
      freeipa_server_install_options: {{ freeipa_server_install_options }}
  debug:
    msg: "{{ msg.split('\n') }}"
    # verbosity: 1

- include_tasks: dependencies.yml

- include_tasks: install-pkgs.yml
  when: freeipa_server_install_pkgs

- include_tasks: install-pip-pkgs.yml
  when: freeipa_server_install_python_pkgs

- include_tasks: preinst.yml

- include_tasks: freeipa-server-install.yml

- include_tasks: pam-mkhomedir-fix.yml
  when: ("--mkhomedir" in freeipa_server_install_options) and
        (ansible_distribution == "Ubuntu") and
        (ansible_distribution_major_version|int <= 16)
