---

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true

- include_tasks: dependencies.yml

- include_tasks: install-pkgs.yml
  when: freeipa_server_install_pkgs

- include_tasks: install-pip-pkgs.yml
  when: freeipa_server_install_python_pkgs

- include_tasks: preinst.yml

- include_tasks: freeipa-server-install.yml
  when: freeipa_server_run_installer
