---

# Following this bug workaround:
# - https://bugs.launchpad.net/ubuntu/+source/freeipa/+bug/1336869
# alternative (not used approach)
# - https://bgstack15.wordpress.com/2017/06/26/enabling-mkhomedir-on-ubuntu-for-freeipa/
- name: Fix for mkhomedir option on Ubuntu <= 16.x
  lineinfile:
    path: /etc/pam.d/common-session
    insertafter: '^session.*pam_sss.so'
    regex: '^session.*pam_mkhomedir.so.*'
    line: 'session	optional 	pam_mkhomedir.so skel=/etc/skel/'
  when: ("--mkhomedir" in freeipa_server_install_options) and
        (ansible_distribution == "Ubuntu") and
        (ansible_distribution_major_version|int <= 16)
