---
- name: Converge
  hosts: all
  roles:
    - role: eengstrom.freeipa-server
      vars:
        - freeipa_admin_password:     'SUPER-SECRET-1'
        - freeipa_ds_password:        'SUPER-SECRET-2'
        - freeipa_server_manage_host: false
